### ISSUE TITLE
Server crash when player joins the world.

### ISSUE THREAD

**Issue by modmuss50** [kumpuu/factorio-helicopters#11]
Hello!

My friend logged out of the server while in a helicopter while it was moving. And upon login the helicopter flew into a rock and crashed the server. He noted that the helicopter had no health at this point.

https://gist.github.com/modmuss50/d5b8bd4ed2d51f1e961417cd4ab43297

I have posted the crash report above, I hope you can use this to fix the issue. Let me know if you have any more questions.

**Comment by kumpuu** [comment]
Hi!
Can you get the save in question for me please? (Clean save, meaning no other mods installed.)

**Comment by modmuss50** [comment]
Hmm, Ill see if I have a backup of the map before we were forced to remove the mod. But we were using a small set of other mods. I wont be able to check till tomorrow however.
