### ISSUE TITLE
[0.16.50] Error while running event (entering helicopter)

### ISSUE THREAD

**Issue by basilgohar** [kumpuu/factorio-helicopters#14]
After some Factorio updates, my helicopter causes a crash to menu when I attempt to enter it, mine it, or destroy it.  Screenshot of the error is here:

![2018-06-11_factorio_helicopters_error_crash-to-menu](https://user-images.githubusercontent.com/43361/41351945-f02c4b4a-6ee5-11e8-8c85-2f183db195bb.png)

The full error message is:

> Error while running event
> Helicopters::on_player_driving_changed_state (ID 26)
> __Helicopters__/control.lua:316 bad argument #1 to 'ipairs' (table expected, got nil)

I posted it on the forums and a couple people have already said it's mod-related and not a Factorio bug, so I wanted to take a shot and open an issue here.  Here's the Factorio forum thread:

https://forums.factorio.com/viewtopic.php?f=7&p=367367#p367367

Affected save and complete mods list can be found here:

https://drive.google.com/open?id=1DHgRRa2byOwqbUb1dfEBC1Ft2uCX9gu4

Possible useful comment from the forum (but may be related to another mod I mentioned):

>That probably means the mod has a broken on_configuration_changed handler, and deleted the old register. You'll just have to rebuild all of them. I.e. it happens because an update happend, not particularly because this update happend. And unless the mod is fixed it's going to happen on every update.

**Comment by kumpuu** [comment]
I think only Allah could fix it.

**Comment by basilgohar** [comment]
What can I do to help fix this issue, or at least narrow down the cause if it's not yet clear?

**Comment by speedfreak01** [comment]
Have the same issue as well running a server. 
This is the error thrown to console on crash. 

`6036.704 Error MainLoop.cpp:1035: Exception at tick 33892839: Error while running event Helicopters::on_player_driving_changed_state (ID 26)
__Helicopters__/control.lua:316: bad argument #1 to 'ipairs' (table expected, got nil)
6036.704 Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running event Helicopters::on_player_driving_changed_state (ID 26)
__Helicopters__/control.lua:316: bad argument #1 to 'ipairs' (table expected, got nil)"
6036.704 Info ServerMultiplayerManager.cpp:699: mapTick(33892839) changing state from(InGame) to(Failed)`

Also running 0.16.50
