### ISSUE TITLE
Belt interactions in 0.16.12

### ISSUE THREAD

**Issue by trevjonez** [kumpuu/factorio-helicopters#3]
Factorio version: 0.16.12
Mod version: 0.2.12

First thing I noticed is that when flying over belts you get a jarring graphic shift.
Then I noticed that inserters stop working when hovering over a belt.

![image](https://user-images.githubusercontent.com/5386503/34500533-61d94d6c-efc8-11e7-8268-d9a983b5a895.png)

**Comment by trevjonez** [comment]
looks like hovering over the top of a train car has a similar effect.
I expect this is a technical limitation because we are sharing 2d space?

**Comment by kumpuu** [comment]
What do you mean by jarring shift? Image looks normal to me. Nearby inserters get disabled automatically since 0.2.11, because they can pick stuff from flying helis. You can disable it in the settings if you want.
And what is a train car? Some mod?

**Comment by trevjonez** [comment]
Every time I fly over a belt the whole screen shifts a few pixels and the audio of the helicoper resets as if I had just started the engine for take off. 

As for the train car I mean the regular cargo wagon, falls under the same behavior as the chests I would figure. 

What it feels like is when I fly over the belt, the belt moves me on the first tick and then the mod prevents any further movement from happening?

**Comment by kumpuu** [comment]
I see. I can't reproduce the belt issue, and the belt immunity is done by the game anyway (they added the option for cars in 0.16 (and the heli is based on the car)) so I think it's a factorio bug. Please let them know on the forum and attach a video or gif to show them what's going on.
I get the audio reset tho, everytime I fly over a belt between two mining drills. Only there, nowhere else on the map. Also a factorio bug I think.
