### ISSUE TITLE
Feature Req: Setting for default zoom level of landing pad view window.

### ISSUE THREAD

**Issue by trevjonez** [kumpuu/factorio-helicopters#6]
I have been adding landing pads at each of the modules of my base and labeling them with text plates. It would be nice if the landing pads could be named directly or if I could at least set the default zoom of the window in the remote control GUI.

![image](https://user-images.githubusercontent.com/5386503/35840555-56c8f2fe-0ab4-11e8-876e-4e3026c36041.png)

as you can see. easily readable at max zoom, not so much at default

**Comment by kumpuu** [comment]
Made a new setting for default zoom.
